[supervisord]
nodaemon=true
logfile=/dev/stdout
loglevel=debug

[program:mcp_server]
command=uvicorn cement_plant_control_system.mcp_server.main:app --host 0.0.0.0 --port 8080
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:leaf_agent]
command=python cement_plant_control_system/leaf_agent/leaf_agent.py
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:main_agent]
command=python cement_plant_control_system/main_agent/main_agent.py
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0